### PR TITLE
#2148 Linkage of order to customer via graphql

### PR DESCRIPTION
**Pull request by riha112**
Original issue: [#2148](https://github.com/scandipwa/scandipwa/issues/2148)

### In this PR:
* Created new mutation to link order to customer after order is placed.

### CODE REVIEW

**Review by yeegor — CHANGES_REQUESTED** [review]
I assume this mutation is intended to be used after a user has logged in.
Hence, their ID can (and should) be derived from the context (`$context->getUserId()` as I remember).
The current solution is unsafe in a sense that it allows setting any customer for any order placed by a guest user.

**Comment by riha112** [comment]
Added security fixes so that only last order within customers session is linked to account.

**Review by yeegor — CHANGES_REQUESTED** [review]
The used ID is still not derived from context, why? Is the user not logged in at the point of calling this mutation? Deriving user ID from context, I believe, will work faster than the current solution.

**Comment by riha112** [comment]
> The used ID is still not derived from context, why? Is the user not logged in at the point of calling this mutation? Deriving user ID from context, I believe, will work faster than the current solution.

If configuration for "Require Email Confirmation" is set to true, then user will not be logged in.

**Review by yeegor — APPROVED** [review]
Alright.

**Pull request merged**
