### PR TITLE
Adapted placeOrder and setPaymentMethodOnCart

### PR DESCRIPTION
**Pull request by atravkovs**

### CODE REVIEW

**Comment by alfredsgenkins** [comment]
Is `2.3.3` required?

**Comment by atravkovs** [comment]
> Is Magento `2.3.3` required?

Yes, thanks for noting.

**Comment by alfredsgenkins** [comment]
If yes, update composer deps. The `createBraintreeClientToken` is for sure from `2.3.3`.

**Comment by atravkovs** [comment]
Update, actualy this PR wraps methods introduced in M2 GraphQL `2.3.2` (`placeOrder` and `setPaymentMethodOnCart`), while `createBraintreeClientToken` is dependency of base-theme, but it does not appear here.

**Pull request merged**
